name: Generate snake game from github contribution grid
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate color for day of week
        id: color
        # RGB + CMYK = 7 week days
        run: echo "color=$(echo 'red green blue cyan magenta violet black' | cut -d ' ' -f `date +%u`)" >> "$GITHUB_OUTPUT"
      - name: generate github-snake.svg
        # uses: aelassas/snk/svg-only@main
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=${{ steps.color.outputs.color }}
            dist/github-snake.svg?palette=github-dark
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/generate-snake-game-from-github-contribution-grid
# https://github.com/Platane/Platane
